apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/GregoryKucherkov/ArgoCD-helm-app.git
    # targetRevision: "master"
    targetRevision: 362526cf36efe31ef15596233617190b8cad2b9d
    path: nginx
    # chart: nginx
    # helm:
    #   values: |
    #     image:
    #       tag: "latest"
    #     service:
    #       type: ClusterIP
    #     ingress:
    #       enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
